### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by clincks** [CollinAlpert/Lombok.NET#6] opened 2022-03-07 02:02 UTC
Hi,

I installed with NuGet Lombok.NET into my project.

I created the minimal code from the example:

```c#
using Lombok.NET;
using System;

namespace com.clinckart.TackITEasy.Lombok
{
    [AllArgsConstructor]
    [With]
    [ToString]
    public partial class Person
    {
        [Property]
        private string _name;
        [Property]
        private int _age;
    }
    class Program
    {
        public static void Main()
        {
            var person = new Person("Steve", 22);
            person = person.WithName("Collin");

            Console.WriteLine(person.Name); // Prints "Collin"
        }
    }
}
```

But VS says that the constructor is not existing and Person doesn't contains definition of WithName and Name.

Any idea what is wrong ?

Thanks

**Comment by CollinAlpert** [comment] 2022-03-07 09:08
VS is sometimes a bit fussy when it comes to recognizing Source Generators. I have copied your source code and tested that it works with VS. You should still be able to build and for me the IntelliSense errors disappeared after closing and reopening the solution. Can you try that and let me know if it works for you? Also, what version of Lombok.NET are you using?

**Comment by CollinAlpert** [comment] 2022-04-06 16:34
I will close this for now since I could not reproduce the issue. Feels free to reopen with some additional context.

**Closed as completed by CollinAlpert** 2022-04-06 16:34 UTC
