### ISSUE TITLE
WithMethodsGenerator has stopped generating file

### ISSUE THREAD

**Issue by ercinakyuz** [CollinAlpert/Lombok.NET#5] opened 2022-02-16 15:28 UTC
<img width="1292" alt="with-stopped" src="https://user-images.githubusercontent.com/36792743/154296959-0e9e39b0-1117-4358-b93c-93126d520036.png">

- Plugin stopped after change property name in class.
- WithAttribute generates WithD method for named Id property. There is something problem with "I" char?

**Comment by CollinAlpert** [comment] 2022-02-16 16:40
Thanks for the issue. I have an idea as to why this is and am working on a fix.

**Comment by CollinAlpert** [comment] 2022-02-16 17:11
Actually I can't reproduce the "WithD" issue. What version of Lombok.NET are you using? Can you send me the build output?

**Comment by ercinakyuz** [comment] 2022-02-17 06:07
<img width="543" alt="Screenshot_3" src="https://user-images.githubusercontent.com/36792743/154415516-af2676c1-592b-400f-a918-cd9220301768.png">
<img width="263" alt="Screenshot_6" src="https://user-images.githubusercontent.com/36792743/154415518-4ca0df8c-7949-4e85-a6f9-5d5af819212a.png">
<img width="640" alt="Screenshot_5" src="https://user-images.githubusercontent.com/36792743/154415521-03c8886e-0676-44e2-a06e-fd3a8f0e58de.png">
<img width="416" alt="Screenshot_2" src="https://user-images.githubusercontent.com/36792743/154415522-7cc9f4fe-ad61-46f9-8b51-82eef5049f8a.png">

Microsoft Visual Studio Community 2022 (64-bit) 
Version 17.0.1
Net 6.0 Console App
Lombok Version: 0.5.1

**Comment by CollinAlpert** [comment] 2022-02-17 10:19
I see, in your case `id` is a private field and not a property. Lombok.NET assumes the naming conventions for private fields, which would mean the field would need to be named `_id`. I am preparing the first stable release and will add checks to ensure that these cases work as well.

**Comment by CollinAlpert** [comment] 2022-02-17 12:13
Fixed in ee788bb01a6e62eaa1bf5923853479b0b57a6241 and 6af871013397b11f4fb53314f093b8fd969f3b1c.

**Closed as completed by CollinAlpert** 2022-02-17 12:13 UTC
